### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by d35e87w** [VeibaeMCC/VeibaeConfigs#11]
我fdp一切你配置就崩怎么回事

**Comment by d35e87w** [comment]
[minecraft-exported-crash-info-2022-05-10T09-17-58.zip](https://github.com/VeibaeMCC/VeibaeConfigs/files/8656330/minecraft-exported-crash-info-2022-05-10T09-17-58.zip)

**Comment by VeibaeMCC** [comment]
等我这两天看看，现在忙
