### ISSUE TITLE
fdp

### ISSUE THREAD

**Issue by xuziangh** [VeibaeMCC/VeibaeConfigs#12]
fdp的dev之一辱华，请不要再使用傻逼的fdp了
![I 74MJDJZ)LMPHJLRA9 _AT](https://user-images.githubusercontent.com/103920679/167754269-0ef4ef39-adaf-4411-b6a8-27c319f17e1b.JPG)
![A5W~D)(_)0JEK9XE`}5RT)6](https://user-images.githubusercontent.com/103920679/167754278-21cb4177-eaaa-4bf3-9ca7-cd4159aad64a.JPG)
![6%QU_ B7JE5O@ RWWDJ_8H9](https://user-images.githubusercontent.com/103920679/167754287-20923d3c-7dbb-4529-be75-c4cd712fec19.JPG)
![ROTP$_RT5AVB {GLOA TJ3Y](https://user-images.githubusercontent.com/103920679/167754302-6a945705-6839-46c9-89c2-5fffcc4a79f0.JPG)

**Comment by VeibaeMCC** [comment]
西瓜和我说他在钓鱼。。。

**Comment by xuziangh** [comment]
你见过这么钓鱼的吗？

**Comment by xuziangh** [comment]
西瓜已经被余志文远控了，所有账号全部被盗
