### ISSUE TITLE
不支持鸣谢辱华者

### ISSUE THREAD

**Issue by SakurajimaMai02** [VeibaeMCC/VeibaeConfigs#13]

**Comment by VeibaeMCC** [comment]
好的采纳啦

**Comment by FCI0UZjzbGSnO4l0rIs** [comment]
**动态网自由门天安门天安门法轮功李洪志Free Tibet 六四天安门事件The Tiananmen Square protests of 1989 天安门大屠杀The Tiananmen Square Massacre 反右派斗争The Anti-Rightist Struggle 大跃进政策The Great Leap Forward 文化大革命The Great Proletarian Cultural Revolution 人权Human Rights 民运Democratization 自由Freedom 独立Independence 多党制Multi-party system 台湾台湾Taiwan Formosa 中华民国Republic of China 西藏土伯特唐古特Tibet 达赖喇嘛Dalai Lama 法轮功Falun Dafa 新疆维吾尔自治区The Xinjiang Uyghur Autonomous Region 诺贝尔和平奖Nobel Peace Prize 刘暁波Liu Xiaobo 民主言论思想反共反革命抗议运动骚乱暴乱骚扰扰乱抗暴平反维权示威游行李洪志法轮大法大法弟子强制断种强制堕胎民族净化人体实验肃清胡耀邦赵紫阳魏京生王丹还政于民和平演变激流中国北京之春大纪元时报评论共产党 独裁 专制 压制 统一 监视 镇压 迫害 侵略 掠夺 破坏 拷问 屠杀 活摘器官 诱拐 买卖人口 游进 走私 毒品 卖淫 春画 赌博 六合彩 天安门 天安门 法轮功 李洪志 Winnie the Pooh 刘晓波动态网自由门 。

在前苏联和东欧各国共产党政权倒台十几年后的今天，世界共产主义运动早已被全世界所唾弃，中国共产党走入坟墓也只是一个时间的问题。

但是中共在彻底垮台之前，却力图将其命运与具有五千年文明历史的中华古国绑在一起，这是我们民族的大不幸。如何看待共产党，如何过渡到一个没有共产党的社会，如何延续我们民族的薪火传承，已经是摆在中国人民面前的一个具体问题了。
大纪元将于今天开始发表特别系列社论《九评共产党》，给为祸人间一个多世纪的国际共产主义运动，特别是中国共产党盖棺论定。

纵观八十多年的中国共产党历史，其所到之处永远伴随着谎言、战乱、饥荒、独裁、屠杀和恐惧；传统的信仰和价值观被共产党强力破坏；原有的伦理观念和社会体系被强制解体；人与人之间的关爱与和谐被扭曲成斗争与仇恨；对天地自然的敬畏与珍惜变成妄自尊大的“战天斗地”，由此带来的社会道德体系和生态体系的全面崩溃，将中华民族乃至整个人类拖向深重的危机。而这一切灾难都在共产党精密的策划、组织和控制下发生着。

“无可奈何花落去”，现今苟延残喘的共产政权已经日暮途穷，它们的崩溃指日可待。在其彻底灭亡之前，我们有必要全面反思和揭露这个集古今中外邪恶之大全的最大邪教组织，让仍旧被共产政权欺骗的人们认清它十恶俱全的本质，从精神上肃清共产党的流毒，从心理上摆脱共产邪灵的控制，跳出恐惧的枷锁，放弃对共产党的一切幻想。

中国共产党的统治是中国历史上最黑暗，也最荒谬的一页，又以江泽民发动的对“真善忍”的镇压最为邪恶。这场运动给中共的棺材钉上了最后一颗钉子。反思这段历史，是为了让这样的悲剧永不再发生。同时我们每一个人也能由此省思自己的内心世界，是否很多本不该发生的悲剧却因为我们的懦弱和妥协而得以成全。**

**Comment by liulihaocai** [comment]
是这样的
CHINA IS A PIECE OF SHIT
TAIWAN NO. 1
