### ISSUE TITLE
you are so funny.

### ISSUE THREAD

**Issue by ll11l1lIllIl1lll** [VeibaeMCC/VeibaeConfigs#1413]
希望你有一天可以认清真相。
希望你不会被中国共产党压迫后，被中国共产党反说一句造谣。

![Image](https://user-images.githubusercontent.com/88377095/176701149-13aa7a79-8bea-4632-a0ba-fea6ea508c36.png)

当然，你也可以选择活在你自己的世界，可以选择不接受这些事情。没有人在强迫你。
![Image](https://user-images.githubusercontent.com/88377095/176703387-abb030bb-49e6-499f-ad7a-880b73de741b.png)

**Comment by VeibaeMCC** [comment]
sorry , funny too , could give a "muuua" to me ? Baby .
